language: rust
rust:
  - 1.28.0 # Minimum supported version
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    packages:
      - pulseaudio
      - libpulse-mainloop-glib0
script:
  - dbus-launch pulseaudio --start
  # Check PA v10 & v11 support
  - cargo build --no-default-features --verbose --all
  - cargo test --no-default-features --verbose --all
  # Check PA v12+ support
  - cargo build --features pa_v12_compatibility --verbose --all
  - cargo test --features pa_v12_compatibility --verbose --all
